language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install tox-travis coveralls

script:
  - tox
  - coverage run --source democritus --module py.test

after_success:
  - coveralls